import re

def process_line(line):
        
    line = re.sub('20', ' ', line)
    line = re.sub('61', 'a', line)
    line = re.sub('62', 'b', line)
    line = re.sub('63', 'c', line)
    line = re.sub('64', 'd', line)
    line = re.sub('65', 'e', line)
    line = re.sub('66', 'f', line)
    line = re.sub('67', 'g', line)
    line = re.sub('68', 'h', line)
    line = re.sub('69', 'i', line)
    line = re.sub('6a', 'j', line)
    line = re.sub('6b', 'k', line)
    line = re.sub('6c', 'l', line)
    line = re.sub('6d', 'm', line)
    line = re.sub('6e', 'n', line)
    line = re.sub('6f', 'o', line)
    line = re.sub('70', 'p', line)
    line = re.sub('71', 'q', line)
    line = re.sub('72', 'r', line)
    line = re.sub('73', 's', line)
    line = re.sub('74', 't', line)
    line = re.sub('75', 'u', line)
    line = re.sub('76', 'v', line)
    line = re.sub('77', 'w', line)
    line = re.sub('78', 'x', line)
    line = re.sub('79', 'y', line)
    line = re.sub('7a', 'z', line)
    line = re.sub('3a', ':', line)
    line = re.sub('2f', '/', line)
    line = re.sub('2e', '.', line)
    line = re.sub('23', '#', line)
    line = re.sub('22', '"', line)
    line = re.sub('3b', ';', line)
    line = re.sub('3c', '<', line)
    line = re.sub('3d', '=', line)
    line = re.sub('3e', '>', line)
    line = re.sub('28', '(', line)
    line = re.sub('29', ')', line)

    print(line)

line1=raw_input()

process_line(line1)
